#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# This tests the new DAGMan feature which propagates halts to sub-DAGs
# (gittrac #5621).
# It works by setting up a .dag file which includes a sub-DAG. When a halt
# file is generated (and later removed) for the main DAG, we verfiy that a 
# halt file is automatically created and later removed for the sub-DAG.


use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_halt-B.dag';
$testdesc =  'Condor submit dag - halt subdag propagation test - scheduler U';
$testname = "job_dagman_halt-B";
$dagman_args = "-verbose -maxpre 1";

$node_output_file = "job_dagman_halt-B.nodes.out";
$halt_file = "job_dagman_halt-B.dag.halt";

# Note: we must find these lines *in the specified order*.
@node_output_lines = ("Node NodeWaitUnhalt starting", 
            "  NodeWaitUnhalt sleeping and checking for halt file",
            "Node NodeHalt starting", 
            "  NodeHalt halting DAG", 
            "  NodeWaitUnhalt found halt file", 
            "Node NodeHalt succeeded", 
            "Node NodeHalt Post script",
            "  NodeWaitUnhalt removing halt file");

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my $rescuedag = $cmd . ".rescue001";

# Get rid of the node output file and rescue DAG if they exist.
if (-e $node_output_file) {
	runcmd("rm -f $node_output_file");
}
if (-e $rescuedag) {
	runcmd("rm -f $rescuedag");
}
if (-e $haltfile) {
	runcmd("rm -f $haltfile");
}

$abnormal = sub 
{
	die "Want to see only submit, execute and termination\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	CondorTest::debug("Good. We need the dag to run\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("DAG succeeded as expected\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	# Make sure all expected lines are in the node output file, in the
	# correct order.
	$checkline = shift @node_output_lines;
	open(CHECK, "<$node_output_file") ||
			die "Cannot open $node_output_file: $!\n";
	while (<CHECK>) {
		chomp();
		$line = $_;
		if ($line eq $checkline) {
			CondorTest::debug("$line\n", 1);
			$checkline = shift @node_output_lines;
			if ( ! (defined $checkline)) {
				# Found all of the lines we expected.
				last;
			}
		}
	}
	close(CHECK);

	if ( (defined $checkline)) {
		unshift @node_output_lines, $checkline;
	}
	while ($checkline = shift @node_output_lines) {
		$diditpass = 0;
		CondorTest::debug("Missing or out-of-order line <$checkline> in $node_output_file\n");
	}

	if($diditpass == 0) {
		die "Expected files and/or correct output failed";
	}

};

$failure = sub
{
	die("DAG is expected to succeed.\n");
};

CondorTest::RegisterExitedFailure( $testname, $failure);
CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

