#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# This tests the NO_POST_ON_FAIL feature (gittrac #6214).  
# * Both nodes (A and B) run a simple perl job which returns 1, indiciating a
#   failure. However both nodes include a POST script which runs successfully.
# * Node A does not have NO_POST_ON_FAIL set (it default to False). Because the
#   job fails but POST script succeeds, node A is successful.
# * Node B has NO_POST_ON_FAIL set to true. So after the job fails, it skips the
#   POST script, and node B fails.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_no_post_on_fail.dag';
$testdesc =  'Condor submit dag - basic no_post_on_fail node test A - scheduler U';
$testname = "job_dagman_no_post_on_fail";
$dagman_args = "-verbose";

$logfile = "job_dagman_no_post_on_fail.dag.dagman.out";
@outfiles = ("job_dagman_no_post_on_fail-A.out", 
    "job_dagman_no_post_on_fail-B.out",
    "job_dagman_no_post_on_fail-A.post.out",
    "job_dagman_no_post_on_fail-B.post.out",
    "job_dagman_no_post_on_fail.dag.rescue001");
my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log and output files
if (-e $logfile) {
	runcmd("rm -f $logfile");
}
foreach $name (@outfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

$abnormal = sub 
{
	die "Want to see only submit, execute and failed completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and failure\n",1);
};

$failure = sub
{
	CondorTest::debug("DAG failed as expected\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	if (! -e "job_dagman_no_post_on_fail-A.post.out") {
		CondorTest::debug("Error: Node A did not run POST script\n");
		$diditpass = 0;
	} else {
		CondorTest::debug("Node A ran its POST script, as expected\n");
	}
	if (-e "job_dagman_no_post_on_fail-B.post.out") {
		CondorTest::debug("Error: Node B ran its POST script!\n");
		$diditpass = 0;
	} else {
		CondorTest::debug("Node B did not run its POST script, as expected\n");
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

$success = sub
{
	die "Error: DAG should fail!\n";
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	if (! -e $logfile) {
		die "$testname: failed -- no $logfile file!  DAG not run?\n";
	}
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}
